############################ CONFIGURATION ############################

#DEFINES += QUADRETOPOLOGY_DEBUG_SAVE_MESHES
#DEFINES += ASSERT_FOR_NUMBER_SIDES
#DEFINES += GUROBI_NON_VERBOSE
#DEFINES += NDEBUG
