./quad_from_patches ./../../test/LoopyCuts/1/1_rem_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/12/12_rem_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/3_holes/3_holes_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/4/4_rem_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/5/5_rem_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/6/6_rem_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/anc_101_a1/MIQ/anc_101_a1_rem_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/anc_101_a1/NPoly/anc_101_a1_rem_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/angel/angel_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/anti_backlash_nut/0/MIQ/anti_backlash_nut_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/anti_backlash_nut/0/NPoly/anti_backlash_nut_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/anti_backlash_nut/1/MIQ/anti_backlash_nut_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/anti_backlash_nut/1/NPoly/anti_backlash_nut_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/armadillo/0/armadillo_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/armadillo/1/armadillo_rem_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/armadillo_mauri/armadillo_mauri_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/asm007/asm007_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/bamboo_pen/bamboo_pen_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/bamboo_pen_rem/0/bamboo_pen_rem_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/bamboo_pen_rem/1/bamboo_pen_rem_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/bear0/bear0_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/bear1/bear1_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/bearing_plate/bearing_plate_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/BendTube/BendTube_rem_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/beveled_shoulder_1/beveled_shoulder_1_rem_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/beveled_shoulder_2/beveled_shoulder_2_rem_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/bigguy/bigguy_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/bimba/bimba_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/blade/blade_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/bladefem/bladefem_rem_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/blech/blech_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/blockLP/blockLP_rem_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/boat/boat_rem_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/bolt/bolt_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/bone/bone_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/bone1/bone1_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/botijo/botijo_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/bozbezbozzel/bozbezbozzel_rem_clean_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/BracketInches/0/BracketInches_rem_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/BracketInches/1/BracketInches_rem_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/bumpy/bumpy_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/bunny/bunny_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/bunny_alessia/bunny_alessia_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/buste/buste_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/busto_bimba/busto_bimba_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/cactus/cactus_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/camille_hand/camille_hand_rem_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/cap_thing/cap_thing_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/carter/carter_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/casting/casting_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/casting/casting_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/cat/cat_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/chinese_lion/chinese_lion_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/clef/clef_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/complex_knot/complex_knot_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/CoverSlipCleaningHolder2b/CoverSlipCleaningHolder2b_rem_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/cube/cube_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/cube_carved/cube_carved_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/cube_minus_sphere/cube_minus_sphere_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/cup/cup_rem_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/cylinder_plate/cylinder_plate_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/dancer/dancer_rem_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/dancing_children/dancing_children_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/deckel/deckel_rem_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/delta_arm_base/0/delta_arm_base_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/delta_arm_base/1/delta_arm_base_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/des6/0/des6_rem_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/des6/1/des6_rem_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/des7/0/des7_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/des7/1/des7_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/dino0/dino0_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/dino1/dino1_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/dog/dog_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/double_torus/double_torus_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/doubletorus/doubletorus_rem_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/dragon0/dragon0_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/duck/duck_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/elephant/elephant_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/ellipse/ellipse_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/eraser_ball/eraser_ball_rem_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/fandisk/MIQ/fandisk_new_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/fandisk/NPoly/fandisk_new_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/fertility/0/fertility_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/fertility/1/fertility_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/fish0/fish0_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/fusee/fusee_Lp_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/gargoyle/0/gargoyle_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/gargoyle/1/gargoyle_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/gear/gear_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/graylock/graylock_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/greek/greek_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/guy/guy_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/gyroidpuzzle/MIQ/gyroidpuzzle_rem_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/gyroidpuzzle/NPoly/gyroidpuzzle_rem_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/halved_oblique_scarf_1/halved_oblique_scarf_1_rem_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/halved_oblique_scarf_2/halved_oblique_scarf_2_rem_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/halved_oblique_scarf_3/halved_oblique_scarf_3_rem_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/hand/hand_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/hinge/hinge_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/holes2/holes2_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/Hub/Hub_rem_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/impeller/impeller_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/indorelax/indorelax_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/inlay_dovetail_1/0/inlay_dovetail_1_rem_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/inlay_dovetail_1/1/inlay_dovetail_1_rem_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/inlay_dovetail_3/inlay_dovetail_3_rem_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/israel/israel_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/joint/0/joint_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/joint/1/joint_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/kitten/kitten_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/knob/knob_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/knot/knot_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/kong/kong_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/lego/0/lego_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/lego/1/lego_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/lever_arm/lever_arm_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/lion/lion_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/lock_Lp/MIQ/lock_Lp_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/lock_Lp/NPoly/lock_Lp_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/LowerControlArm/LowerControlArm_rem_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/mazewheel/mazewheel_rem_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/mech09/0/mech09_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/mech09/1/mech09_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/mech10/mech10_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/mech_piece/mech_piece_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/mechanical01/mechanical01_rem_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/mechanical02/mechanical02_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/mechanical03/mechanical03_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/mechanical04/mechanical04_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/mechanical05/mechanical05_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/mechanical06/mechanical06_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/mechanical07/mechanical07_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/mechanical08/mechanical08_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/metatron/MIQ/metatron_rem_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/metatron/NPoly/metatron_rem_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/mid2Fem/mid2Fem_rem_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/mnf07HeadFem/mnf07HeadFem_rem_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/motor_tail/motor_tail_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/mount/mount_rem_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/mouse/0/mouse_rem_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/mouse/1/mouse_rem_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/mechanical01/mechanical01_rem_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/nasty_cheese/MIQ/nasty_cheese_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/nasty_cheese/NPoly/nasty_cheese_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/no_name/no_name_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/nugear/nugear_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/octopus/octopus_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/pegaso/pegaso_rem_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/pig/pig_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/pinion/MIQ/pinion_rem_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/pinion/NPoly/pinion_rem_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/plate_lp/plate_lp_mid_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/prism/prism_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/pump/0/pump_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/pump/1/pump_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/rabbit/rabbit_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/rockerarm/rockerarm_rem_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/rod/rod_rem_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/RotorHub/MIQ/RotorHub_rem_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/RotorHub/NPoly/RotorHub_rem_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/santa/santa_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/sculpt/sculpt_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/shaft/shaft_rem_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/sharp_sphere/sharp_sphere_rem_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/sphinx/sphinx_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/spring/spring_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/square_torus/square_torus_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/teapot/teapot_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/thai/0/thai_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/thai/1/thai_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/toothbrush_holder/toothbrush_holder_rem_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/torque/torque_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/torque1/torque1_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/torus/torus_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/torus2/torus2_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/TransmissionHousingFem/0/TransmissionHousingFem_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/TransmissionHousingFem/1/TransmissionHousingFem_rem_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/trebol/trebol_rem_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/tris_closed/tris_closed_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/tris_open/tris_open_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/turbine_lp/turbine_lp_rem_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/ujoint/ujoint_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/vase0/vase0_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/Vertebrae/Vertebrae_rem_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/wave/wave_rem_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/wedge/wedge_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/wedge_with_base/0/wedge_with_base_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/wedge_with_base/1/wedge_with_base_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/WheelDassault/WheelDassault_rem_rem_p0.obj 0
./quad_from_patches ./../../test/LoopyCuts/wrench/wrench_rem_p0.obj 0
